#!/bin/sh

cd "$(dirname "$0/")"

pippath=`which pip3`
sudo $pippath install .

PATHTOEXECUTABLE=`which system-monitor | sed -e "s/\//\\\\\\\\\//g"`
sudo cp systemmonitor.service /etc/systemd/system/
sudo sed -i -e "s/\/usr\/bin\/system-monitor/$PATHTOEXECUTABLE/" /etc/systemd/system/systemmonitor.service
sudo cp systemmonitor.timer /etc/systemd/system/
